# Generated by Django 5.1.2 on 2024-11-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
